### ISSUE TITLE
segfault at random

### ISSUE THREAD

**Issue by Congee** [hhatto/python-hoedown#6]
Test script below:
```
for i in {1..1000};
do hoedownpy posts/How-to-setup-ghost-on-DigitalOcean-doplets.md> /dev/null
	if [[ $? != 0 ]]; then
		echo $i
	fi
done
```
I've tested the markdown file with original hoedown which worked fine.

[The markdown file tested on gist](https://gist.github.com/congee/16d1d67a43bbd7a14523)
PS: I'm using python3.4 on Mac OS X 10.10.2

**Comment by hhatto** [comment]
fix in version 0.2.3.
